#!/bin/bash
rm -rf /mnt/stg_w02/var/www/fresh/css
rm -rf /mnt/stg_w02/var/www/fresh/js
rm  /mnt/stg_w02/var/www/fresh/index.html
rm -rf /mnt/stg_w02/var/www/fresh/fonts

cp -R dist/{js,css,index.html,fonts} /mnt/stg_w02/var/www/fresh/
chmod g+w dist/{js,css,fonts}/* 
chmod g+w dist/index.html 
