#!/bin/bash
rm -rf /mnt/stg_w03/var/www/vod-serv2/css
rm -rf /mnt/stg_w03/var/www/vod-serv2/js
rm  /mnt/stg_w03/var/www/vod-serv2/index.html
rm -rf /mnt/stg_w03/var/www/vod-serv2/fonts

cp -R dist/{js,css,index.html,fonts} /mnt/stg_w03/var/www/vod-serv2/
chmod g+w dist/{js,css,fonts}/* 
chmod g+w dist/index.html 
