version: "3.8"

services:
  vue_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
