#!/bin/bash
rm -rf /mnt/stg_w02/var/www/work/css
rm -rf /mnt/stg_w02/var/www/work/js
rm  /mnt/stg_w02/var/www/work/index.html
rm -rf /mnt/stg_w02/var/www/work/fonts

cp -R dist/{js,css,index.html,fonts} /mnt/stg_w02/var/www/work/
chmod g+w dist/{js,css,fonts}/* 
chmod g+w dist/index.html 
