#!/bin/bash
rm -rf /mnt/stg_w02/var/www/ls-rental/admin/css
rm -rf /mnt/stg_w02/var/www/ls-rental/admin/js
rm  /mnt/stg_w02/var/www/ls-rental/admin/index.html
rm -rf /mnt/stg_w02/var/www/ls-rental/admin/fonts

cp -R dist/{js,css,index.html,fonts} /mnt/stg_w02/var/www/ls-rental/admin/
chmod g+w dist/{js,css,fonts}/* 
chmod g+w dist/index.html 
