#!/bin/bash
rm -rf /mnt/stg_w02/var/www/strateg-new/css
rm -rf /mnt/stg_w02/var/www/strateg-new/js
rm  /mnt/stg_w02/var/www/strateg-new/index.html
rm -rf /mnt/stg_w02/var/www/strateg-new/fonts

cp -R dist/{js,css,index.html,fonts} /mnt/stg_w02/var/www/strateg-new/
chmod g+w dist/{js,css,fonts}/* 
chmod g+w dist/index.html 
