#!/bin/bash
rm -rf /mnt/stg_w03/var/www/vod-serv/css
rm -rf /mnt/stg_w03/var/www/vod-serv/js
rm  /mnt/stg_w03/var/www/vod-serv/index.html
rm -rf /mnt/stg_w03/var/www/vod-serv/fonts

cp -R dist/{js,css,index.html,fonts} /mnt/stg_w03/var/www/vod-serv/
chmod g+w dist/{js,css,fonts}/* 
chmod g+w dist/index.html 
